# Generated by Django 5.1.4 on 2025-02-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MIH', 'MODERN_INDIAN_HISTORY'), ('HAC', 'HISTORY_ART_AND_CULTURE'), ('POL', 'POLITY'), ('IRS', 'INTERNATIONAL_RELATIONS_AND_SECURITY'), ('ECO', 'ECONOMICS'), ('SNT', 'SCIENCE_AND_TECH'), ('ENV', 'ENVIRONMENT'), ('GEO', 'GEOGRAPHY'), ('SOCI', 'SOCIAL_ISSUES'), ('MISC', 'MISCELLANEOUS')], max_length=4)),
                ('question_content_type', models.CharField(choices=[('STATIC', 'STATIC'), ('CA', 'CURRENT_AFFAIRS')], max_length=6)),
                ('pattern_type', models.CharField(choices=[('SINGLE_STATEMENT', 'SINGLE_STATEMENT'), ('TWO_STATEMENTS', 'TWO_STATEMENTS'), ('THREE_STATEMENTS', 'THREE_STATEMENTS'), ('IDENTIFY_FEATURES', 'IDENTIFY_FEATURES'), ('MATCH_THE_PAIRS', 'MATCH_THE_PAIRS')], max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('explanation', models.TextField()),
            ],
            options={
                'db_table': 'prelims_mock_mcq',
                'ordering': ['pattern_type'],
            },
        ),
        migrations.CreateModel(
            name='PYQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('q_num', models.PositiveIntegerField()),
                ('subject', models.CharField(choices=[('MIH', 'MODERN_INDIAN_HISTORY'), ('HAC', 'HISTORY_ART_AND_CULTURE'), ('POL', 'POLITY'), ('IRS', 'INTERNATIONAL_RELATIONS_AND_SECURITY'), ('ECO', 'ECONOMICS'), ('SNT', 'SCIENCE_AND_TECH'), ('ENV', 'ENVIRONMENT'), ('GEO', 'GEOGRAPHY'), ('SOCI', 'SOCIAL_ISSUES'), ('MISC', 'MISCELLANEOUS')], max_length=4)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
                ('explanation', models.TextField()),
            ],
            options={
                'db_table': 'prelims_pyq',
                'ordering': ['year', 'q_num'],
                'unique_together': {('year', 'q_num')},
            },
        ),
    ]
