# Generated by Django 5.1.4 on 2025-01-17 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.TextField()),
            ],
            options={
                'db_table': 'prelims_explanation',
            },
        ),
        migrations.CreateModel(
            name='PYQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('MIH', 'Modern Indian History'), ('HAC', 'History, Art & Culture'), ('POL', 'Polity'), ('IR', 'International Relations'), ('ECO', 'Economics'), ('ST', 'Science & Technology'), ('ENV', 'Environment'), ('GEO', 'Geography'), ('MISC', 'Miscellaneous')], max_length=4)),
                ('question_text', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('q_num', models.PositiveIntegerField()),
                ('explanation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions.explanation')),
            ],
            options={
                'db_table': 'prelims_pyq',
                'ordering': ['year', 'q_num'],
                'unique_together': {('year', 'q_num')},
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('option_num', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.pyquestion')),
            ],
            options={
                'db_table': 'prelims_options',
                'ordering': ['option_num'],
                'unique_together': {('question', 'option_num')},
            },
        ),
    ]
