# Generated by Django 5.1.4 on 2025-01-18 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explanation',
            new_name='Explanations',
        ),
        migrations.RenameModel(
            old_name='PYQuestion',
            new_name='PYQuestions',
        ),
        migrations.AlterModelTable(
            name='explanations',
            table='prelims_explanations',
        ),
        migrations.AlterModelTable(
            name='pyquestions',
            table='prelims_pyqs',
        ),
    ]
