# Generated by Django 5.1.4 on 2025-01-17 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='question',
        ),
        migrations.AddField(
            model_name='pyquestion',
            name='explanation',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions.explanation'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='options',
            unique_together={('question', 'option_num')},
        ),
        migrations.AlterUniqueTogether(
            name='pyquestion',
            unique_together={('year', 'q_num')},
        ),
    ]
