# Generated by Django 5.1.4 on 2025-01-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_explanation_explanations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyquestions',
            name='subject',
            field=models.CharField(choices=[('MIH', 'MODERN_INDIAN_HISTORY'), ('HAC', 'HISTORY_ART_AND_CULTURE'), ('POL', 'POLITY'), ('IR', 'INTERNATIONAL_RELATIONS'), ('ECO', 'ECONOMICS'), ('ST', 'SCIENCE_AND_TECH'), ('ENV', 'ENVIRONMENT'), ('GEO', 'GEOGRAPHY'), ('MISC', 'MISCELLANEOUS')], max_length=4),
        ),
    ]
